# Title: Facebook Post Success Predictor
# Author: Enoch Cheung 
# date: 2023-04-23


# 0: Run all
all: data/facebook.csv data/facebook.csv data/train_set.csv data/test_set.csv results/01_meanLikesByPostType.png


# 01: Load data
data/facebook.csv:	R/01_read_data_from_URL.R
	Rscript R/01_read_data_from_URL.R --url="https://raw.githubusercontent.com/calamari99/dsci-310-group-12-dreamteam/main/data/dataset_Facebook.csv" --out_dir="data"

#02: Read csv facebook_data and Clean data using R script
data/facebook_clean.csv: data/facebook.csv R/02_clean_data.R 
	Rscript R/02_clean_data.R --input_dir="data/facebook.csv" --out_dir="data"

#03: Read csv facebook_clean and split unpaid data using R script
data/train_set.csv data/test_set.csv: data/facebook_clean.csv R/03_split_unpaid_data.R 
	Rscript R/03_split_unpaid_data.R --input_dir="data/facebook_clean.csv" --out_dir="data"

#04: Produce Preprocessing EDA figures
results/01_meanLikesByPostType.png results/02_meanInteractionsPostType: data/train_set.csv R/04_EDA.R 
	Rscript R/04_EDA.R  --input_dir="data/train_set.csv" --out_dir="results"

